version: 2.1

executors:
  my-executor:
    docker:
      - image: douggernaut/threeagent-ci:0.0.1
    working_directory: /tmp/workspace

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run:
          name: Installing npm deps
          command: npm install
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

  test:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run:
          name: Building cljs
          command: lein cljsbuild once test
      - run:
          name: Running karma tests
          command: /tmp/workspace/node_modules/.bin/karma start --single-run
      - store_test_results:
          path: reports

  render_test:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run:
          name: Building cljs
          command: lein cljsbuild once render-test
      - run:
          name: "Running render test"
          command: node ./tests/render_test/run.js
      - store_artifacts:
          path: /tmp/workspace/tests/render_test/diff.png

  deploy_snapshot:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Deploying to clojars
          command: lein deploy clojars

  release_rc:
    executor: my-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "05:a7:54:63:4e:af:8f:6f:27:4c:57:26:50:a9:5e:00"
      - run:
          command: |
            git config --global user.email "circleci@circleci"
            git config --global user.name "Release Script"
      - run:
          name: Release rc
          command: lein release :rc

  release:
    executor: my-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "05:a7:54:63:4e:af:8f:6f:27:4c:57:26:50:a9:5e:00"
      - run:
          command: |
            git config --global user.email "circleci@circleci"
            git config --global user.name "Release Script"
      - run:
          name: Release rc
          command: lein release :patch

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build

      - render_test:
          requires:
            - build

      - deploy_snapshot:
          filters:
            branches:
              only:
                - "master"
          requires:
            - test
            - render_test

      - release_rc:
          filters:
            branches:
              only: /^release$/
          requires:
            - test
            - render_test
